<?php

namespace App\Tools\HttpStatusCodes;

class HttpStatusCodes
{
    public static function codes(): array
    {
        return [
            // ── 1xx Informational ──────────────────────────────────────────
            ['code' => 100, 'name' => 'Continue',             'category' => '1xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server has received the request headers and the client should proceed to send the request body.'],
            ['code' => 101, 'name' => 'Switching Protocols',  'category' => '1xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server agrees to switch protocols as requested by the client via the Upgrade header (e.g. HTTP → WebSocket).'],
            ['code' => 102, 'name' => 'Processing',           'category' => '1xx', 'rfc' => 'RFC 2518',
             'desc' => 'WebDAV: the server has received and is processing the request but no response is available yet.'],
            ['code' => 103, 'name' => 'Early Hints',          'category' => '1xx', 'rfc' => 'RFC 8297',
             'desc' => 'Allows the server to send preliminary response headers (e.g. Link preload) while the final response is being prepared.'],

            // ── 2xx Success ────────────────────────────────────────────────
            ['code' => 200, 'name' => 'OK',                          'category' => '2xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request succeeded. The meaning depends on the HTTP method used (GET, POST, PUT, etc.).'],
            ['code' => 201, 'name' => 'Created',                     'category' => '2xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request succeeded and a new resource was created. The URI of the new resource is typically in the Location header.'],
            ['code' => 202, 'name' => 'Accepted',                    'category' => '2xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request has been accepted for processing but the processing has not been completed (asynchronous operations).'],
            ['code' => 203, 'name' => 'Non-Authoritative Information', 'category' => '2xx', 'rfc' => 'RFC 9110',
             'desc' => 'The returned metadata was collected from a third-party copy rather than from the origin server.'],
            ['code' => 204, 'name' => 'No Content',                  'category' => '2xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request succeeded but there is no content to send in the response body. Often used for DELETE or PUT.'],
            ['code' => 205, 'name' => 'Reset Content',               'category' => '2xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request succeeded. The client should reset the document view (e.g. clear a form).'],
            ['code' => 206, 'name' => 'Partial Content',             'category' => '2xx', 'rfc' => 'RFC 9110',
             'desc' => 'Partial GET: the server is delivering only part of the resource due to a Range header sent by the client.'],
            ['code' => 207, 'name' => 'Multi-Status',                'category' => '2xx', 'rfc' => 'RFC 4918',
             'desc' => 'WebDAV: the response body contains multiple separate responses for multiple independent operations.'],
            ['code' => 208, 'name' => 'Already Reported',            'category' => '2xx', 'rfc' => 'RFC 5842',
             'desc' => 'WebDAV: the members of a DAV binding have already been enumerated in a previous reply.'],
            ['code' => 226, 'name' => 'IM Used',                     'category' => '2xx', 'rfc' => 'RFC 3229',
             'desc' => 'The server has fulfilled a GET request for the resource and the response represents the result of one or more instance-manipulations.'],

            // ── 3xx Redirection ────────────────────────────────────────────
            ['code' => 300, 'name' => 'Multiple Choices',    'category' => '3xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request has more than one possible response. The user-agent should choose one.'],
            ['code' => 301, 'name' => 'Moved Permanently',   'category' => '3xx', 'rfc' => 'RFC 9110',
             'desc' => 'The resource has been permanently moved to a new URL given in the Location header. Search engines update their index.'],
            ['code' => 302, 'name' => 'Found',               'category' => '3xx', 'rfc' => 'RFC 9110',
             'desc' => 'The resource is temporarily at a different URL. The client should continue using the original URL for future requests.'],
            ['code' => 303, 'name' => 'See Other',           'category' => '3xx', 'rfc' => 'RFC 9110',
             'desc' => 'The response to the request can be found at another URI using GET. Used after a POST to redirect to a confirmation page.'],
            ['code' => 304, 'name' => 'Not Modified',        'category' => '3xx', 'rfc' => 'RFC 9110',
             'desc' => 'The cached version is still valid. The server signals the client to use its cached copy (conditional GET).'],
            ['code' => 307, 'name' => 'Temporary Redirect',  'category' => '3xx', 'rfc' => 'RFC 9110',
             'desc' => 'Temporary redirect that preserves the HTTP method. Unlike 302, the method must not change (POST stays POST).'],
            ['code' => 308, 'name' => 'Permanent Redirect',  'category' => '3xx', 'rfc' => 'RFC 9110',
             'desc' => 'Permanent redirect that preserves the HTTP method. Unlike 301, the method must not change.'],

            // ── 4xx Client Error ───────────────────────────────────────────
            ['code' => 400, 'name' => 'Bad Request',                        'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server cannot process the request due to a client error (malformed syntax, invalid framing, deceptive routing).'],
            ['code' => 401, 'name' => 'Unauthorized',                       'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'Authentication is required and has failed or not been provided. The response must include a WWW-Authenticate header.'],
            ['code' => 402, 'name' => 'Payment Required',                   'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'Reserved for future use. Originally intended for digital payment systems; used by some APIs for quota exceeded.'],
            ['code' => 403, 'name' => 'Forbidden',                          'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server understood the request but refuses to authorize it. Unlike 401, authentication will not help.'],
            ['code' => 404, 'name' => 'Not Found',                          'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server cannot find the requested resource. May be temporary or permanent; used also to hide a 403.'],
            ['code' => 405, 'name' => 'Method Not Allowed',                 'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The HTTP method is known but not supported for the target resource. The Allow header lists valid methods.'],
            ['code' => 406, 'name' => 'Not Acceptable',                     'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'Content negotiation failed: the server cannot produce a response matching the Accept-* headers sent by the client.'],
            ['code' => 407, 'name' => 'Proxy Authentication Required',      'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'Authentication with a proxy server is required. Similar to 401, but authentication is for a proxy.'],
            ['code' => 408, 'name' => 'Request Timeout',                    'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server timed out waiting for the request. The client may repeat the request.'],
            ['code' => 409, 'name' => 'Conflict',                           'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request could not be processed because of a conflict in the current state of the resource (e.g. edit conflict).'],
            ['code' => 410, 'name' => 'Gone',                               'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The resource is permanently gone from the server with no forwarding address. Unlike 404, this is intentional and final.'],
            ['code' => 411, 'name' => 'Length Required',                    'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request did not specify the length of its content. The server requires a Content-Length header.'],
            ['code' => 412, 'name' => 'Precondition Failed',                'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'One or more conditions given in the request header fields (If-Match, If-Unmodified-Since) evaluated to false.'],
            ['code' => 413, 'name' => 'Content Too Large',                  'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request entity is larger than limits defined by the server. Formerly called "Request Entity Too Large".'],
            ['code' => 414, 'name' => 'URI Too Long',                       'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The URI provided was too long for the server to process. Often caused by encoding too much data into a GET query string.'],
            ['code' => 415, 'name' => 'Unsupported Media Type',             'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The media format of the request body is not supported by the server (check Content-Type header).'],
            ['code' => 416, 'name' => 'Range Not Satisfiable',              'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The range specified in the Range header cannot be fulfilled (e.g. beyond the end of the file).'],
            ['code' => 417, 'name' => 'Expectation Failed',                 'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The Expect request-header field could not be met by the server.'],
            ['code' => 418, 'name' => "I'm a Teapot",                       'category' => '4xx', 'rfc' => 'RFC 2324',
             'desc' => 'Any attempt to brew coffee with a teapot should result in this error. An April Fools joke that became an internet standard.'],
            ['code' => 421, 'name' => 'Misdirected Request',                'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request was directed at a server that is not able to produce a response (connection reuse mismatch or routing error).'],
            ['code' => 422, 'name' => 'Unprocessable Content',              'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The request was well-formed but could not be followed due to semantic errors (e.g. invalid JSON field values).'],
            ['code' => 423, 'name' => 'Locked',                             'category' => '4xx', 'rfc' => 'RFC 4918',
             'desc' => 'WebDAV: the resource that is being accessed is locked.'],
            ['code' => 424, 'name' => 'Failed Dependency',                  'category' => '4xx', 'rfc' => 'RFC 4918',
             'desc' => 'WebDAV: the request failed because it depended on another request which failed.'],
            ['code' => 425, 'name' => 'Too Early',                          'category' => '4xx', 'rfc' => 'RFC 8470',
             'desc' => 'The server is unwilling to risk processing a request that might be replayed (TLS 1.3 early data).'],
            ['code' => 426, 'name' => 'Upgrade Required',                   'category' => '4xx', 'rfc' => 'RFC 9110',
             'desc' => 'The client should switch to a different protocol (given in the Upgrade header), such as TLS/1.3.'],
            ['code' => 428, 'name' => 'Precondition Required',              'category' => '4xx', 'rfc' => 'RFC 6585',
             'desc' => 'The origin server requires the request to be conditional (to prevent lost update problems).'],
            ['code' => 429, 'name' => 'Too Many Requests',                  'category' => '4xx', 'rfc' => 'RFC 6585',
             'desc' => 'The user has sent too many requests in a given amount of time (rate limiting). Retry-After header may indicate when to retry.'],
            ['code' => 431, 'name' => 'Request Header Fields Too Large',    'category' => '4xx', 'rfc' => 'RFC 6585',
             'desc' => 'The server is unwilling to process the request because its header fields are too large (individual header or total size).'],
            ['code' => 451, 'name' => 'Unavailable For Legal Reasons',      'category' => '4xx', 'rfc' => 'RFC 7725',
             'desc' => 'The resource is unavailable due to a legal demand such as a court order or government-mandated censorship.'],

            // ── 5xx Server Error ───────────────────────────────────────────
            ['code' => 500, 'name' => 'Internal Server Error',           'category' => '5xx', 'rfc' => 'RFC 9110',
             'desc' => 'A generic error message when the server encountered an unexpected condition that prevented it from fulfilling the request.'],
            ['code' => 501, 'name' => 'Not Implemented',                 'category' => '5xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server does not support the functionality required to fulfill the request (unknown method).'],
            ['code' => 502, 'name' => 'Bad Gateway',                     'category' => '5xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server, acting as a gateway or proxy, received an invalid response from the upstream server.'],
            ['code' => 503, 'name' => 'Service Unavailable',             'category' => '5xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server is not ready to handle the request (maintenance or overload). Retry-After may indicate recovery time.'],
            ['code' => 504, 'name' => 'Gateway Timeout',                 'category' => '5xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server, acting as a gateway or proxy, did not get a response in time from the upstream server.'],
            ['code' => 505, 'name' => 'HTTP Version Not Supported',      'category' => '5xx', 'rfc' => 'RFC 9110',
             'desc' => 'The server does not support the HTTP protocol version used in the request.'],
            ['code' => 506, 'name' => 'Variant Also Negotiates',         'category' => '5xx', 'rfc' => 'RFC 2295',
             'desc' => 'Transparent content negotiation for the request results in a circular reference (server misconfiguration).'],
            ['code' => 507, 'name' => 'Insufficient Storage',            'category' => '5xx', 'rfc' => 'RFC 4918',
             'desc' => 'WebDAV: the server is unable to store the representation needed to complete the request.'],
            ['code' => 508, 'name' => 'Loop Detected',                   'category' => '5xx', 'rfc' => 'RFC 5842',
             'desc' => 'WebDAV: the server detected an infinite loop while processing the request.'],
            ['code' => 510, 'name' => 'Not Extended',                    'category' => '5xx', 'rfc' => 'RFC 2774',
             'desc' => 'Further extensions to the request are required for the server to fulfill it.'],
            ['code' => 511, 'name' => 'Network Authentication Required', 'category' => '5xx', 'rfc' => 'RFC 6585',
             'desc' => 'The client needs to authenticate to gain network access (captive portal on public Wi-Fi).'],
        ];
    }

    public static function categories(): array
    {
        return ['1xx', '2xx', '3xx', '4xx', '5xx'];
    }
}
